name: 'Test Report'
on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: jdk17-test-results
          name: JDK 17 Tests
          path: '**/*.xml'
          reporter: java-junit
